services:

    postgres:
        image: postgres
        container_name: postgres
        ports:
            - 5432:5432
        volumes:
            - db-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=${DB_PASS}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_DB=${DB_NAME}
        networks:
            - pong-network
        restart: on-failure

    nginx-server:
        build: ./frontend
        image: nginx-server
        container_name: nginx-server
        ports:
            - 8080:80
        environment:
            - NGINX_HOST=localhost
            - NGINX_PORT=80
        volumes:
            - ./frontend/app:/usr/share/nginx/html/app
        networks:
            - pong-network
        restart: on-failure

    pgadmin4:
        image: dpage/pgadmin4
        container_name: pgadmin4
        ports:
            - 3000:80
        environment:
            - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
            - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASS}
        networks:
            - pong-network
        restart: on-failure

networks:
    pong-network:
        name: pong-network

volumes:
  db-data:
    name: db-data
    driver_opts:
      type: none
      device: ${DB_VOLUME_DATA}
      o: bind
